//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOCC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Visitor
    {
        public int Id { get; set; }
        [Display(Name = "病人名稱")]
        public string Pat_name { get; set; }
        [Display(Name = "病人病歷號碼")]
        public string MedRec_no { get; set; }
        [Display(Name = "病床號碼")]
        public string Bed_no { get; set; }
        [Display(Name = "預約日期")]
        public string Reserve_date { get; set; }
        [Display(Name = "訪客身分證或居留證")]
        public string Id_no { get; set; }
        [Display(Name = "訪客姓名")]
        public string Name { get; set; }
        [Display(Name = "訪客電話")]
        public int Phone_num { get; set; }
        [Display(Name = "訪客與病人的關係")]
        public string Identity { get; set; }
        [Display(Name = "訪客旅遊史")]
        public string Travel_history { get; set; }
        [Display(Name = "訪客職業別")]
        public string Occupation { get; set; }
        [Display(Name = "接觸史")]
        public string Contact_history { get; set; }
        [Display(Name = "群聚史")]
        public string Cluster { get; set; }
        [Display(Name = "到期日")]
        public string Expiry_date { get; set; }
        [Display(Name = "評估項目")]
        public string Evaluation_item { get; set; }
    }
}
